version: "3.8"

services:
  rooms-db:
    image: postgres:16-alpine
    container_name: rooms-hotel-db
    environment:
      POSTGRES_DB: rooms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - rooms-db-data:/var/lib/postgresql/data
    networks:
      - microservicios-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rooms_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  reservations-db:
    image: postgres:16-alpine
    container_name: reservations-hotel-db
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - reservations-db-data:/var/lib/postgresql/data
    networks:
      - microservicios-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reservations_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  svc-rooms:
    build:
      context: ./svc-rooms
      dockerfile: Dockerfile
    container_name: svc-rooms-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rooms-db:5432/rooms_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    networks:
      - microservicios-network
    depends_on:
      rooms-db:
        condition: service_healthy

  svc-reservations:
    build:
      context: ./svc-reservations
      dockerfile: Dockerfile
    container_name: svc-reservations-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservations-db:5432/reservations_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    networks:
      - microservicios-network
    depends_on:
      reservations-db:
        condition: service_healthy
      svc-rooms:
        condition: service_started

  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservicios-network
    depends_on:
      - svc-rooms
      - svc-reservations

volumes:
  rooms-db-data:
  reservations-db-data:
networks:
  microservicios-network:
    driver: bridge
