spring.application.name=svc-reservations
server.port=8082

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5434/reservations_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

#URL de comunicacion (svc-rooms)
rooms.service.url=http://svc-rooms:8081

#Resilience4j - Circuit breaker
resilience4j.circuitbreaker.instances.catalogService.sliding-windows-size=5
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=3

#Resilience4j - Retry
resilience4j.circuitbreaker.instances.catalogService.max-attempts=3
resilience4j.circuitbreaker.instances.catalogService.wait-duration=2s

#Resilience4j - Timeout
resilience4j.circuitbreaker.instances.catalogService.timeout-duration=3s